"""empty message

Revision ID: 1e082cd44f3e
Revises: None
Create Date: 2015-04-16 12:31:28.726610

"""

# revision identifiers, used by Alembic.
revision = '1e082cd44f3e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
