"""empty message

Revision ID: 524796b5773a
Revises: None
Create Date: 2015-01-21 09:26:16.334639

"""

# revision identifiers, used by Alembic.
revision = '524796b5773a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
